import csv
import easygui
import pandas as pd

def compare_var_resp():
    print("Step - 1")
    #browse for Response analysis file
    global variance_file_path
    Response_path = easygui.fileopenbox(title="Please browse the Response Variance Data file generated by Survey")

    #op variance file
    variance_file_path = 'Op_Variance_Data.csv'
    print("Step - 2" + variance_file_path)
    A = pd.read_csv(variance_file_path, engine='python')
    print("Step - 2A")
    B = pd.read_excel(Response_path)
    print("Step - 2B")
    print("Step - 3")
    #email_ids of Responded practioners
    Response_email_id = B['2. Email ID:'].tolist()
    practioners_responded = len(Response_email_id)
    #email_ids of all the practitioners
    Variance_emai_id = A['Email_Id'].tolist()
    Total_practitioners= len(Variance_emai_id)
    Send_email = A['Send_Email'].tolist()
    print("Step - 4")
    #Modifying the data of Send email column to No if found in Response list
    with open(variance_file_path,newline="") as file:
        readData=[row for row in csv.DictReader(file)]

        for i in range(practioners_responded):
            for j in range(Total_practitioners):
                if Response_email_id[i].upper()==readData[j]['Email_Id'].upper():
                    readData[j]['Send_Email'] = 'No'
    print("Step - 5")

    header=readData[0].keys()
    print("Step - 6")
    #Updating OP_Variance CSV file
    with open(variance_file_path,'w',newline="") as updated_csv:
        #updated_csv.writerows(readData)
        writer = csv.DictWriter(updated_csv, fieldnames = header)
        writer.writeheader()
        writer.writerows(readData)
    A = pd.read_csv(variance_file_path, engine='python')
    Send_email = A['Send_Email'].tolist()
    print("Step - 7")
    emails_num = Send_email.count('Yes')
    print('Number of Practitioners to be emailed: ' + str(emails_num))
    return emails_num




