import csv
import easygui
import pandas as pd

def compare_var_resp():

    #browse for Response analysis file
    global variance_file_path
    Response_path = easygui.fileopenbox(title="Please browse the Response Variance Data file generated by Survey")

    #op variance file
    variance_file_path = './Op_Variance_Data_sample.csv'

    A = pd.read_csv(variance_file_path)
    B = pd.read_excel(Response_path)

    #email_ids of Responded practioners
    Response_email_id = B['2. Email ID:'].tolist()
    practioners_responded = len(Response_email_id)
    #email_ids of all the practitioners
    Variance_emai_id = A['Email_Id'].tolist()
    Total_practitioners= len(Variance_emai_id)
    Send_email = A['Send_Email'].tolist()

    #Modifying the data of Send email column to No if found in Response list
    with open(variance_file_path,newline="") as file:
        readData=[row for row in csv.DictReader(file)]

        for i in range(practioners_responded):
            for j in range(Total_practitioners):
                if Response_email_id[i].upper()==readData[j]['Email_Id'].upper():
                    readData[j]['Send_Email'] = 'No'


    header=readData[0].keys()

    #Updating OP_Variance CSV file
    with open(variance_file_path,'w',newline="") as updated_csv:
        #updated_csv.writerows(readData)
        writer = csv.DictWriter(updated_csv, fieldnames = header)
        writer.writeheader()
        writer.writerows(readData)
    Send_email = A['Send_Email'].tolist()
    emails_num = Send_email.count('Yes')
    return emails_num

